In [1]:
import numpy as np
def generateDiskGalaxy(galaxySize,maxcharge):
    positions = generateDisk(galaxySize)
    charges = generateCharge(positions,maxcharge)
    return positions,charges

def generateCharge(positions,maxcharge):
    origins = np.zeros_like(positions)
    distances = np.linalg.norm(positions-origins,axis=1) #calculate distance to the origin
    charges = [maxcharge*np.random.normal(d) for d in distances] # more close more likely to have a high charge
    return charges


def generateDisk(galaxySize):
    length = np.sqrt(np.random.uniform(0, 1, galaxySize))
    angle = np.pi * np.random.uniform(0, 2,galaxySize)
    x = length * np.cos(angle)
    y = length * np.sin(angle)
    z = np.random.uniform(-1, 1, galaxySize)
    return list(zip(x,y,z))


In [2]:
a,b = generateDiskGalaxy(10,10)

In [3]:
b

[17.980200142066565,
 7.811889070512217,
 9.301736448100938,
 11.738239312915809,
 20.01356203498199,
 -7.842041360271623,
 12.603078355823465,
 16.015560064734494,
 25.824839733221083,
 29.553159194120994]

In [4]:
np.linalg.norm(np.zeros_like(generateDisk(10))-generateDisk(10),axis=1)

array([1.2529617 , 0.89780231, 0.91597178, 0.89744197, 1.09117278,
       1.27262598, 0.42212136, 0.90799834, 0.95463181, 0.32456272])

In [5]:
from scipy.spatial.distance import cdist


In [6]:
x = np.array([[2,1],[1,1]])
y = np.array([[1,0], [2,3], [4,3]])



In [7]:
cdist(x,y)

array([[1.41421356, 2.        , 2.82842712],
       [1.        , 2.23606798, 3.60555128]])

In [1]:
from Galaxy import Galaxy

In [2]:
a = Galaxy()

In [3]:
a.probelist['0'].galaxy_positions.index(a.probelist['0'].current_position)

0

In [17]:
a.probelist['0'].current_position

(-0.5388927625086042, -0.09864258948075694, -0.7638241567520633)

In [5]:
a.systemPos[760]

(-0.6287782536435658, -0.09732267401432595, -0.8803450268772695)

In [16]:
ok = a.step({"0":["move",760]})

In [23]:
10 in {1:10}

False

In [12]:
import numpy as np
import math

In [13]:
distance = np.linalg.norm(np.array(a.probelist['0'].current_position)-np.array(a.systemPos[760]))
math.ceil(distance/0.02)-1

31

In [16]:
tuple(np.array(a.probelist['0'].current_position)-(np.array(a.probelist['0'].current_position)-np.array(a.systemPos[760]))/distance)

(-0.8612761004083473, -0.7977550660873911, 0.477174390337767)

In [19]:
vars(a.probelist['0'])

{'block': 97,
 'dead': False,
 'destination': (0.3532894239317163, 0.09352986309691536, -0.7313336538809212),
 'id': '0',
 'positions': {'0': [(-0.24594054703045645,
    -0.186607343706005,
    -0.020681631195737182),
   (-0.24594054703045645, -0.186607343706005, -0.020681631195737182)]},
 'system_beliefs': {(-0.24594054703045645,
   -0.186607343706005,
   -0.020681631195737182): [-1723580.7726426264, 1],
  (0.11207597709425422,
   0.2503236132840182,
   0.4691073393062315): [709747.50334104, 0],
  (0.13148605293664917,
   0.028564596035747607,
   0.8104394662885037): [59328.76010308063, 0],
  (0.5584483550651221,
   -0.17902706471752675,
   -0.3176517581235889): [667947.8293540197, 0],
  (0.3916853323403357,
   0.4336446686558636,
   0.01657667842136079): [-136166.0157198016, 0],
  (-0.05748907907377675,
   -0.3148832553216148,
   0.06893966383366457): [-306752.29336342594, 0],
  (0.6560660523939373,
   0.6555431847620738,
   -0.019139051006572982): [1807230.4942322797, 0],
  (-0.3718

In [26]:
ok = a.step({"0":["stay",0]})

In [6]:
ok = a.step({"0":["move",760]})

In [7]:
from scipy.spatial.distance import cdist


In [8]:
cdist((1,0,1),(0,1,0))

ValueError: XA must be a 2-dimensional array.

In [12]:
a.distanceMatrix

array([[0.        , 0.72121428, 1.94910932, ..., 1.37137789, 1.96215944,
        1.30703087],
       [0.72121428, 0.        , 1.47271042, ..., 0.88502348, 1.83207039,
        0.7664825 ],
       [1.94910932, 1.47271042, 0.        , ..., 0.8502108 , 0.9838459 ,
        0.9101728 ],
       ...,
       [1.37137789, 0.88502348, 0.8502108 , ..., 0.        , 1.39415466,
        0.85787739],
       [1.96215944, 1.83207039, 0.9838459 , ..., 1.39415466, 0.        ,
        1.40457925],
       [1.30703087, 0.7664825 , 0.9101728 , ..., 0.85787739, 1.40457925,
        0.        ]])

In [13]:
vars(a.systemlist[0])

{'charge': 996066.3995688444,
 'position': (-0.5264987840911138, 0.6941509078296622, -0.9272088274270298),
 'max_system_charge': 1000000,
 'agents': [],
 'agentrecord': {'replicate': 0,
  'death': 0,
  'stay': 1,
  'visit': 1,
  'recharge': 0}}

In [14]:
from pprint import pprint

In [15]:
pprint(vars(a.probelist['0']))

{'block': -1,
 'charge': 97.02,
 'current_position': array([nan, nan, nan]),
 'dead': False,
 'degradation': 0.01,
 'destination': (-0.5264987840911138, 0.6941509078296622, -0.9272088274270298),
 'galaxy_positions': [(-0.5264987840911138,
                       0.6941509078296622,
                       -0.9272088274270298),
                      (-0.8607562165900318,
                       0.2925100840576635,
                       -0.4301105974679351),
                      (-0.17433996897456525,
                       -0.13890677633408324,
                       0.7993560345735127),
                      (-0.21028835610696445,
                       0.014884434023493442,
                       -0.7265076027031736),
                      (0.4494322023569568,
                       0.12997899333444599,
                       0.15479530059351143),
                      (0.44704161812650317,
                       -0.11110132533367344,
                       0.89828148101687),
         

                       0.3683613306416408,
                       -0.49497988539629256),
                      (0.434303314445884,
                       0.436764019252069,
                       -0.2379332240319183),
                      (-0.004273270191168185,
                       0.22728222426228128,
                       -0.7162335375747697),
                      (-0.22129281438806686,
                       -0.9360121041565194,
                       0.8205371819272191),
                      (-0.4400343302048642,
                       -0.5818154821017737,
                       -0.29543392650526457),
                      (0.05817228593707039,
                       0.5830195010737903,
                       0.8044427533965082),
                      (0.2571671456822424,
                       0.9345486255005467,
                       -0.41520100047981634),
                      (0.40056483104012885,
                       0.6109339336637453,
                       -0.9954

                    (-0.4784285705943069, -0.7421052592732909, -0.344230760962726): [339548.65625405475,
                                                                                     0],
                    (-0.47064095996171007, 0.24938864241496542, -0.9346430417440508): [2697970.494921064,
                                                                                       0],
                    (-0.4687207017358162, 0.6760768444317736, 0.8831861683857019): [-83803.413615811,
                                                                                    0],
                    (-0.4676835792174247, 0.07767914839978948, -0.698243142950679): [454180.055321745,
                                                                                     0],
                    (-0.4642867956906337, 0.24657376153845303, 0.13348986391167883): [-781803.3443319128,
                                                                                      0],
                    (-0.4630905

                                                                                     0],
                    (0.5956758513091611, -0.29642908929647427, -0.9183335461715227): [1715175.4751127132,
                                                                                      0],
                    (0.5967049032063919, -0.019296751169984666, -0.6853786925051313): [2153220.124359885,
                                                                                       0],
                    (0.5996508389439493, -0.22901952644487183, -0.5060986814997879): [411096.36580314,
                                                                                      0],
                    (0.6064606818362892, -0.595293790803594, -0.10556650892486141): [619658.863499896,
                                                                                     0],
                    (0.6068684225921311, -0.18973293697078522, -0.03363701349943882): [-879401.296989049,
                           

In [16]:
10**6

1000000

In [35]:
(np.array([0,1,0])-np.array([1,0,1]))/np.linalg.norm(np.array([0,1,0])-np.array([1,0,1]))

array([-0.57735027,  0.57735027, -0.57735027])